language: python
python:
  - "3.6"
  - "3.7"
sudo: false
services:
    - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libffi-dev libxml2-dev
install:
- pip install -U tox
#- pip install codev
- pip install -r will/requirements/dev.txt
script:
- tox
# - "fab docker_build"
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: "fab docker_deploy"
#   on:
#     branch: master
env:
  matrix:
