site_name: Will's Docs
site_url: http://skoczen.github.io/will
site_description: "Will is a simple, beautiful-to-code python hipchat bot"
pages:
- Get Started: index.md
- Teach Your Will:
  - The Basics: plugins/basics.md
  - What Will Can Notice: plugins/notice.md
  - How Will Can Respond: plugins/reply.md
  - Creating and Organizing Plugins: plugins/create.md
  - Plugin Builtins: plugins/builtins.md
  - Bundled Plugins: plugins/bundled.md
- Configure: config.md
- Deploy: deploy.md
- Improve: improve.md
# theme: will
site_name: Will
theme_dir: "docs/themes/will/"
repo_url: https://github.com/skoczen/will/
copyright: Copyright &copy; 2014, GreenKahuna, Steven Skoczen and the individual contributors.
# google_analytics: ['UA-1234567-8', 'skoczen.github.io/will']
