version: "2.0"

services:
    redis:
        image: redis:alpine
        volumes:
            - ./data/redis:/data
    pcobot:
        image: pastorhudson/pcobot
        ports:
            - 8081:8080
        env_file:
            - default.env
        volumes:
            - ../plugins:/opt/plugins
            - ../config.py:/opt/will/config.py
        depends_on:
            - redis
            
